"""add tenant_id and expires_at to paymentlink

Revision ID: 6ef7d60f5d68
Revises: 9fa5cab23522
Create Date: 2026-04-07 00:03:28.139902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef7d60f5d68'
down_revision = '9fa5cab23522'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add column as nullable first
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # Step 2: (Optional) Set default values for existing rows
    op.execute("UPDATE payment_link SET tenant_id = 1 WHERE tenant_id IS NULL")

    # Step 3: Make tenant_id NOT NULL
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
