"""make settings fields optional

Revision ID: 9b20f111a7b7
Revises: g9h2k4l6m8n0
Create Date: 2026-04-03 14:06:37.392961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b20f111a7b7'
down_revision = 'g9h2k4l6m8n0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('two_factor_code', schema=None) as batch_op:
        batch_op.alter_column('is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('two_factor_code_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('two_factor_verification', schema=None) as batch_op:
        batch_op.alter_column('email_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('sms_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('two_factor_verification_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_two_factor_verification_user_id'))
        batch_op.create_index(batch_op.f('ix_two_factor_verification_user_id'), ['user_id'], unique=True)
        batch_op.drop_constraint(batch_op.f('two_factor_verification_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('message_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_2fa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_2fa_enabled', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_public_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_public_id'))
        batch_op.create_index(batch_op.f('ix_user_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_public_id'))
        batch_op.create_index(batch_op.f('ix_user_public_id'), ['public_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_user_public_id'), ['public_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('email_2fa_enabled')
        batch_op.drop_column('sms_2fa_enabled')
        batch_op.drop_column('message_alerts')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('address')
        batch_op.drop_column('bio')
        batch_op.drop_column('business_name')

    with op.batch_alter_table('two_factor_verification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('two_factor_verification_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_two_factor_verification_user_id'))
        batch_op.create_index(batch_op.f('ix_two_factor_verification_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('two_factor_verification_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('totp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('sms_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('email_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('two_factor_code', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('two_factor_code_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
